// <auto-generated />
using System;
using FISEI.ServiceDesk.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FISEI.ServiceDesk.Infrastructure.Migrations
{
    [DbContext(typeof(ServiceDeskDbContext))]
    [Migration("20251203013752_FixStaticSeedTime")]
    partial class FixStaticSeedTime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FISEI.ServiceDesk.Domain.Entities.ArticuloConocimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etiquetas")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("IncidenciaOrigenId")
                        .HasColumnType("int");

                    b.Property<int?>("LaboratorioId")
                        .HasColumnType("int");

                    b.Property<string>("Referencias")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ServicioId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UltimaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("IncidenciaOrigenId")
                        .HasDatabaseName("IX_KB_IncidenciaOrigen");

                    b.HasIndex("LaboratorioId");

                    b.HasIndex("AutorId", "Activo");

                    b.HasIndex("ServicioId", "LaboratorioId");

                    b.ToTable("ArticulosConocimiento");
                });

            modelBuilder.Entity("FISEI.ServiceDesk.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "Hardware"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Nombre = "Software"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Nombre = "Red"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Nombre = "Acceso"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Nombre = "Audiovisual"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Nombre = "Climatización"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Nombre = "Mobiliario"
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Nombre = "Otro"
                        });
                });

            modelBuilder.Entity("FISEI.ServiceDesk.Domain.Entities.ComentarioIncidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsInterno")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("IncidenciaId")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IncidenciaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ComentariosIncidencia");
                });

            modelBuilder.Entity("FISEI.ServiceDesk.Domain.Entities.Escalacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IncidenciaId")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IncidenciaId");

                    b.ToTable("Escalaciones");
                });

            modelBuilder.Entity("FISEI.ServiceDesk.Domain.Entities.EstadoIncidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("EsFinal")
                        .HasColumnType("bit");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("EstadosIncidencia");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "ABIERTO",
                            EsFinal = false,
                            Orden = 1
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "EN_PROGRESO",
                            EsFinal = false,
                            Orden = 2
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "RESUELTO",
                            EsFinal = false,
                            Orden = 3
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "CERRADO",
                            EsFinal = true,
                            Orden = 4
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "REABIERTO",
                            EsFinal = false,
                            Orden = 5
                        });
                });

            modelBuilder.Entity("FISEI.ServiceDesk.Domain.Entities.FeedbackIncidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("IncidenciaId")
                        .HasColumnType("int");

                    b.Property<byte>("Puntuacion")
                        .HasColumnType("tinyint");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IncidenciaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("FISEI.ServiceDesk.Domain.Entities.Incidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("Cerrada")
                        .HasColumnType("bit");

                    b.Property<int>("CreadorId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUltimoCambio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("LaboratorioId")
                        .HasColumnType("int");

                    b.Property<int>("PrioridadId")
                        .HasColumnType("int");

                    b.Property<int>("ServicioId")
                        .HasColumnType("int");

                    b.Property<int?>("TecnicoAsignadoId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreadorId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("LaboratorioId");

                    b.HasIndex("PrioridadId");

                    b.HasIndex("ServicioId");

                    b.HasIndex("TecnicoAsignadoId");

                    b.ToTable("Incidencias");
                });

            modelBuilder.Entity("FISEI.ServiceDesk.Domain.Entities.Laboratorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Edificio")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Laboratorios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Codigo = "LAB-RED",
                            Edificio = "FISEI",
                            Nombre = "Lab Redes",
                            Ubicacion = "Piso 2"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Codigo = "LAB-SW",
                            Edificio = "FISEI",
                            Nombre = "Lab Software",
                            Ubicacion = "Piso 3"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Codigo = "LAB-HW",
                            Edificio = "FISEI",
                            Nombre = "Lab Hardware",
                            Ubicacion = "Piso 1"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Codigo = "LAB-AV",
                            Edificio = "FISEI",
                            Nombre = "Lab Audiovisual",
                            Ubicacion = "Piso 4"
                        });
                });

            modelBuilder.Entity("FISEI.ServiceDesk.Domain.Entities.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("Leida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioDestinoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioDestinoId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("FISEI.ServiceDesk.Domain.Entities.Prioridad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.Property<int>("TiempoMaxHoras")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Prioridades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Baja",
                            Peso = 1,
                            TiempoMaxHoras = 168
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Media",
                            Peso = 2,
                            TiempoMaxHoras = 72
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Alta",
                            Peso = 3,
                            TiempoMaxHoras = 24
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Crítica",
                            Peso = 4,
                            TiempoMaxHoras = 4
                        });
                });

            modelBuilder.Entity("FISEI.ServiceDesk.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Estudiante"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Tecnico"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Docente"
                        });
                });

            modelBuilder.Entity("FISEI.ServiceDesk.Domain.Entities.SLA_Definicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("HorasResolucion")
                        .HasColumnType("int");

                    b.Property<int>("HorasRespuesta")
                        .HasColumnType("int");

                    b.Property<int>("PrioridadId")
                        .HasColumnType("int");

                    b.Property<int?>("ServicioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrioridadId");

                    b.HasIndex("ServicioId");

                    b.ToTable("SLA_Definiciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            HorasResolucion = 4,
                            HorasRespuesta = 0,
                            PrioridadId = 4
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            HorasResolucion = 24,
                            HorasRespuesta = 1,
                            PrioridadId = 3
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            HorasResolucion = 72,
                            HorasRespuesta = 4,
                            PrioridadId = 2
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            HorasResolucion = 168,
                            HorasRespuesta = 8,
                            PrioridadId = 1
                        });
                });

            modelBuilder.Entity("FISEI.ServiceDesk.Domain.Entities.SLA_Incidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreadoUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("CumplidoResolucion")
                        .HasColumnType("bit");

                    b.Property<bool>("CumplidoRespuesta")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaLimiteResolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaLimiteRespuesta")
                        .HasColumnType("datetime2");

                    b.Property<int>("IncidenciaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IncidenciaId");

                    b.ToTable("SLA_Incidencias");
                });

            modelBuilder.Entity("FISEI.ServiceDesk.Domain.Entities.Seguimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EstadoAnteriorId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoNuevoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("IncidenciaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstadoAnteriorId");

                    b.HasIndex("EstadoNuevoId");

                    b.HasIndex("IncidenciaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Seguimientos");
                });

            modelBuilder.Entity("FISEI.ServiceDesk.Domain.Entities.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Servicios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CategoriaId = 1,
                            Nombre = "Soporte PC"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CategoriaId = 3,
                            Nombre = "Red/Conectividad"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            CategoriaId = 2,
                            Nombre = "Software"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            CategoriaId = 5,
                            Nombre = "Audiovisual"
                        });
                });

            modelBuilder.Entity("FISEI.ServiceDesk.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Correo = "admin1@admin.com",
                            FechaRegistro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Admin 1",
                            PasswordHash = "7bLj4V/UqVZU/y/tYw/jheG+yr1QU1KyWjfOZaCKuKY=",
                            PasswordSalt = "lOvvglGCDYWu2T3sCDzE1A==",
                            RolId = 3
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Correo = "admin2@admin.com",
                            FechaRegistro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Admin 2",
                            PasswordHash = "7bLj4V/UqVZU/y/tYw/jheG+yr1QU1KyWjfOZaCKuKY=",
                            PasswordSalt = "lOvvglGCDYWu2T3sCDzE1A==",
                            RolId = 3
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Correo = "tecnico1@uta.edu.ec",
                            FechaRegistro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Tecnico 1",
                            PasswordHash = "7bLj4V/UqVZU/y/tYw/jheG+yr1QU1KyWjfOZaCKuKY=",
                            PasswordSalt = "lOvvglGCDYWu2T3sCDzE1A==",
                            RolId = 2
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Correo = "tecnico2@uta.edu.ec",
                            FechaRegistro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Tecnico 2",
                            PasswordHash = "7bLj4V/UqVZU/y/tYw/jheG+yr1QU1KyWjfOZaCKuKY=",
                            PasswordSalt = "lOvvglGCDYWu2T3sCDzE1A==",
                            RolId = 2
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Correo = "tecnico3@uta.edu.ec",
                            FechaRegistro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Tecnico 3",
                            PasswordHash = "7bLj4V/UqVZU/y/tYw/jheG+yr1QU1KyWjfOZaCKuKY=",
                            PasswordSalt = "lOvvglGCDYWu2T3sCDzE1A==",
                            RolId = 2
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Correo = "tecnico4@uta.edu.ec",
                            FechaRegistro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Tecnico 4",
                            PasswordHash = "7bLj4V/UqVZU/y/tYw/jheG+yr1QU1KyWjfOZaCKuKY=",
                            PasswordSalt = "lOvvglGCDYWu2T3sCDzE1A==",
                            RolId = 2
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Correo = "docente1@uta.edu.ec",
                            FechaRegistro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Docente 1",
                            PasswordHash = "7bLj4V/UqVZU/y/tYw/jheG+yr1QU1KyWjfOZaCKuKY=",
                            PasswordSalt = "lOvvglGCDYWu2T3sCDzE1A==",
                            RolId = 4
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Correo = "docente2@uta.edu.ec",
                            FechaRegistro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Docente 2",
                            PasswordHash = "7bLj4V/UqVZU/y/tYw/jheG+yr1QU1KyWjfOZaCKuKY=",
                            PasswordSalt = "lOvvglGCDYWu2T3sCDzE1A==",
                            RolId = 4
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            Correo = "docente3@uta.edu.ec",
                            FechaRegistro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Docente 3",
                            PasswordHash = "7bLj4V/UqVZU/y/tYw/jheG+yr1QU1KyWjfOZaCKuKY=",
                            PasswordSalt = "lOvvglGCDYWu2T3sCDzE1A==",
                            RolId = 4
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            Correo = "docente4@uta.edu.ec",
                            FechaRegistro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Docente 4",
                            PasswordHash = "7bLj4V/UqVZU/y/tYw/jheG+yr1QU1KyWjfOZaCKuKY=",
                            PasswordSalt = "lOvvglGCDYWu2T3sCDzE1A==",
                            RolId = 4
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            Correo = "est1@uta.edu.ec",
                            FechaRegistro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Estudiante 1",
                            PasswordHash = "7bLj4V/UqVZU/y/tYw/jheG+yr1QU1KyWjfOZaCKuKY=",
                            PasswordSalt = "lOvvglGCDYWu2T3sCDzE1A==",
                            RolId = 1
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            Correo = "est2@uta.edu.ec",
                            FechaRegistro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Estudiante 2",
                            PasswordHash = "7bLj4V/UqVZU/y/tYw/jheG+yr1QU1KyWjfOZaCKuKY=",
                            PasswordSalt = "lOvvglGCDYWu2T3sCDzE1A==",
                            RolId = 1
                        },
                        new
                        {
                            Id = 13,
                            Activo = true,
                            Correo = "est3@uta.edu.ec",
                            FechaRegistro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Estudiante 3",
                            PasswordHash = "7bLj4V/UqVZU/y/tYw/jheG+yr1QU1KyWjfOZaCKuKY=",
                            PasswordSalt = "lOvvglGCDYWu2T3sCDzE1A==",
                            RolId = 1
                        },
                        new
                        {
                            Id = 14,
                            Activo = true,
                            Correo = "est4@uta.edu.ec",
                            FechaRegistro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Estudiante 4",
                            PasswordHash = "7bLj4V/UqVZU/y/tYw/jheG+yr1QU1KyWjfOZaCKuKY=",
                            PasswordSalt = "lOvvglGCDYWu2T3sCDzE1A==",
                            RolId = 1
                        },
                        new
                        {
                            Id = 15,
                            Activo = true,
                            Correo = "est5@uta.edu.ec",
                            FechaRegistro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Estudiante 5",
                            PasswordHash = "7bLj4V/UqVZU/y/tYw/jheG+yr1QU1KyWjfOZaCKuKY=",
                            PasswordSalt = "lOvvglGCDYWu2T3sCDzE1A==",
                            RolId = 1
                        },
                        new
                        {
                            Id = 16,
                            Activo = true,
                            Correo = "est6@uta.edu.ec",
                            FechaRegistro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Estudiante 6",
                            PasswordHash = "7bLj4V/UqVZU/y/tYw/jheG+yr1QU1KyWjfOZaCKuKY=",
                            PasswordSalt = "lOvvglGCDYWu2T3sCDzE1A==",
                            RolId = 1
                        },
                        new
                        {
                            Id = 17,
                            Activo = true,
                            Correo = "est7@uta.edu.ec",
                            FechaRegistro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Estudiante 7",
                            PasswordHash = "7bLj4V/UqVZU/y/tYw/jheG+yr1QU1KyWjfOZaCKuKY=",
                            PasswordSalt = "lOvvglGCDYWu2T3sCDzE1A==",
                            RolId = 1
                        },
                        new
                        {
                            Id = 18,
                            Activo = true,
                            Correo = "est8@uta.edu.ec",
                            FechaRegistro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Estudiante 8",
                            PasswordHash = "7bLj4V/UqVZU/y/tYw/jheG+yr1QU1KyWjfOZaCKuKY=",
                            PasswordSalt = "lOvvglGCDYWu2T3sCDzE1A==",
                            RolId = 1
                        },
                        new
                        {
                            Id = 19,
                            Activo = true,
                            Correo = "est9@uta.edu.ec",
                            FechaRegistro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Estudiante 9",
                            PasswordHash = "7bLj4V/UqVZU/y/tYw/jheG+yr1QU1KyWjfOZaCKuKY=",
                            PasswordSalt = "lOvvglGCDYWu2T3sCDzE1A==",
                            RolId = 1
                        },
                        new
                        {
                            Id = 20,
                            Activo = true,
                            Correo = "est10@uta.edu.ec",
                            FechaRegistro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Estudiante 10",
                            PasswordHash = "7bLj4V/UqVZU/y/tYw/jheG+yr1QU1KyWjfOZaCKuKY=",
                            PasswordSalt = "lOvvglGCDYWu2T3sCDzE1A==",
                            RolId = 1
                        });
                });

            modelBuilder.Entity("FISEI.ServiceDesk.Domain.Entities.ArticuloConocimiento", b =>
                {
                    b.HasOne("FISEI.ServiceDesk.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FISEI.ServiceDesk.Domain.Entities.Incidencia", null)
                        .WithMany()
                        .HasForeignKey("IncidenciaOrigenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FISEI.ServiceDesk.Domain.Entities.Laboratorio", null)
                        .WithMany()
                        .HasForeignKey("LaboratorioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FISEI.ServiceDesk.Domain.Entities.Servicio", null)
                        .WithMany()
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FISEI.ServiceDesk.Domain.Entities.ComentarioIncidencia", b =>
                {
                    b.HasOne("FISEI.ServiceDesk.Domain.Entities.Incidencia", null)
                        .WithMany()
                        .HasForeignKey("IncidenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FISEI.ServiceDesk.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FISEI.ServiceDesk.Domain.Entities.Escalacion", b =>
                {
                    b.HasOne("FISEI.ServiceDesk.Domain.Entities.Incidencia", null)
                        .WithMany()
                        .HasForeignKey("IncidenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FISEI.ServiceDesk.Domain.Entities.FeedbackIncidencia", b =>
                {
                    b.HasOne("FISEI.ServiceDesk.Domain.Entities.Incidencia", null)
                        .WithMany()
                        .HasForeignKey("IncidenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FISEI.ServiceDesk.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FISEI.ServiceDesk.Domain.Entities.Incidencia", b =>
                {
                    b.HasOne("FISEI.ServiceDesk.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CreadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FISEI.ServiceDesk.Domain.Entities.EstadoIncidencia", null)
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FISEI.ServiceDesk.Domain.Entities.Laboratorio", null)
                        .WithMany()
                        .HasForeignKey("LaboratorioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FISEI.ServiceDesk.Domain.Entities.Prioridad", null)
                        .WithMany()
                        .HasForeignKey("PrioridadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FISEI.ServiceDesk.Domain.Entities.Servicio", null)
                        .WithMany()
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FISEI.ServiceDesk.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("TecnicoAsignadoId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("FISEI.ServiceDesk.Domain.Entities.Notificacion", b =>
                {
                    b.HasOne("FISEI.ServiceDesk.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FISEI.ServiceDesk.Domain.Entities.SLA_Definicion", b =>
                {
                    b.HasOne("FISEI.ServiceDesk.Domain.Entities.Prioridad", null)
                        .WithMany()
                        .HasForeignKey("PrioridadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FISEI.ServiceDesk.Domain.Entities.Servicio", null)
                        .WithMany()
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FISEI.ServiceDesk.Domain.Entities.SLA_Incidencia", b =>
                {
                    b.HasOne("FISEI.ServiceDesk.Domain.Entities.Incidencia", null)
                        .WithMany()
                        .HasForeignKey("IncidenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FISEI.ServiceDesk.Domain.Entities.Seguimiento", b =>
                {
                    b.HasOne("FISEI.ServiceDesk.Domain.Entities.EstadoIncidencia", null)
                        .WithMany()
                        .HasForeignKey("EstadoAnteriorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FISEI.ServiceDesk.Domain.Entities.EstadoIncidencia", null)
                        .WithMany()
                        .HasForeignKey("EstadoNuevoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FISEI.ServiceDesk.Domain.Entities.Incidencia", null)
                        .WithMany()
                        .HasForeignKey("IncidenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FISEI.ServiceDesk.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FISEI.ServiceDesk.Domain.Entities.Servicio", b =>
                {
                    b.HasOne("FISEI.ServiceDesk.Domain.Entities.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
